#!/bin/bash

# Enhanced Docker launcher with proper user management
# This script addresses the permission issues with Yocto/Poky builds

flexbuild_launch_docker_user() {
    local username=$(whoami)
    local user_id=$(id -u)
    local group_id=$(id -g)
    
    dnum=$(echo $FBDIR | md5sum | cut -b 1-6)
    prefix="${DOCKER_CONTAINER_PREFIX:-}"
    containername=${prefix}${username}_fbdebian_user_${DEBIAN_VERSION}_${dnum}
    
    # Build the user-aware Docker image if it doesn't exist
    if ! docker images | grep -q "fbdebian-user.*${DEBIAN_VERSION}"; then
        echo "Building user-aware Docker image..."
        make -C $FBDIR/docker/debian -f Makefile.user build-user
    fi
    
    # Create container if it doesn't exist
    if ! docker ps -a | grep -q $containername; then
        echo "Creating new container: $containername"
        docker run -t -i -d \
            --name="$containername" \
            --hostname=fbdebian \
            --privileged=true \
            --net=host \
            -v $HOME:$HOME \
            -v $FBDIR:$FBDIR \
            -v /lib/modules:/lib/modules \
            -v /dev:/dev \
            -v /etc/localtime:/etc/localtime:ro \
            --add-host=fbdebian:127.0.0.1 \
            -w $FBDIR \
            -u $username \
            fbdebian-user:${DEBIAN_VERSION} \
            /bin/bash
            
        # Attach to the container
        docker attach $containername
        
    elif docker ps -a | grep $containername | grep -q Exited; then
        echo "Starting existing container: $containername"
        docker start $containername
        docker attach $containername
    else
        echo "Attaching to running container: $containername"
        docker attach $containername
    fi
}

# Alternative function for running single commands
flexbuild_docker_exec() {
    local username=$(whoami)
    local user_id=$(id -u)
    local group_id=$(id -g)
    
    dnum=$(echo $FBDIR | md5sum | cut -b 1-6)
    prefix="${DOCKER_CONTAINER_PREFIX:-}"
    containername=${prefix}${username}_fbdebian_user_${DEBIAN_VERSION}_${dnum}
    
    # Build the user-aware Docker image if it doesn't exist
    if ! docker images | grep -q "fbdebian-user.*${DEBIAN_VERSION}"; then
        echo "Building user-aware Docker image..."
        make -C $FBDIR/docker/debian -f Makefile.user build-user
    fi
    
    # Run command in container
    docker run --rm -t \
        --hostname=fbdebian \
        --privileged=true \
        --net=host \
        -v $HOME:$HOME \
        -v $FBDIR:$FBDIR \
        -v /lib/modules:/lib/modules \
        -v /dev:/dev \
        -v /etc/localtime:/etc/localtime:ro \
        --add-host=fbdebian:127.0.0.1 \
        -w $FBDIR \
        -u $username \
        fbdebian-user:${DEBIAN_VERSION} \
        "$@"
}

# Export functions for use
export -f flexbuild_launch_docker_user
export -f flexbuild_docker_exec
